from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
from src.config.enviornments import EnviornmentVariables
env = EnviornmentVariables()
# This secure connect bundle is autogenerated when you donwload your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': str(env.cassandra_connect.bundle_connect)
}

# This token json file is autogenerated when you donwload your token, 
# if yours is different update the file name below
with open(str(env.cassandra_connect.token_json)) as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()