version: "2"

networks:
  cassandra:
    driver: bridge

services: 
  pyspark:
    image: avnish327030/pyspark-3.2.1:latest
    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    volumes:
      - "./pyspark_files:/project"
    networks:
      - cassandra
